---
title: "Final script for cleaning DI"
format: html
---
```{r}
#Load in relevant libraries
library("dplyr")
library("tidyverse")
```
```{r}

#Load in and read disease information.txt

data <-read.delim("disease_information.txt", header = TRUE, stringsAsFactors = FALSE)

#looking at data structure
head(data)
```
```{r}
#check the dimensions and for missing values
dim(data)
nrow(data)
ncol(data)
summary(data)
```
```{r}
any(is.na(data))
sum(is.na(data))
```
```{r}
data %>% summarise(across(everything(), ~ sum(is.na(.x))))

duplicated(data)
```
```{r}
all(grepl("^DOID", data$disease_id))
all(grepl("^OMIM", data$OMIM.IDs))
all(grepl("^MGI", data$Mouse.MGI.ID))
```

```{r}
# Rename the column names to remove (.) and replace with (_)
data <- data %>% 
  rename(OMIM_IDs = OMIM.IDs)
data <- data %>% 
  rename(DO_Disease_ID = DO.Disease.ID)
data <- data %>% 
  rename(DO_Disease_name = DO.Disease.Name)
data <- data %>% 
  rename(Mouse_MGI_ID = Mouse.MGI.ID)

colnames(data)
head(data)
```
```{r}
#Count how many rows have multiple OMID IDs
multiple_omims <- sum(grepl("\\|", data$OMIM_IDs))
cat("Rows with multiple OMIM IDs:", multiple_omims, "\n\n")
```
```{r}
#Data quality checks for OMIM, disease, and mouse gene identifiers
cat("Any missing OMIM_IDs:", sum(is.na(data$OMIM_IDs)), "\n")
cat("Any empty OMIM_IDs:", sum(data$OMIM_IDs == ""), "\n")
cat("Unique OMIM IDs:", n_distinct(data$OMIM_IDs), "\n")
cat("Unique diseases:", n_distinct(data$DO_Disease_ID), "\n")
cat("Unique mouse genes:", n_distinct(data$Mouse_MGI_ID), "\n")
```
```{r}
output_file <- "DI_clean_updated.csv"
write_csv(data, output_file)
```


